":musical_note: Audio":
  - changed-files:
    - any-glob-to-any-file: "**/*.ogg"

":shark: C#":
  - changed-files:
    - any-glob-to-any-file: "**/*.cs"

":gear: Config":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.toml"
      - "**/*.config"
      - "*.json"
      - ".github/*.yml"
      - ".github/*.json"
      - ".vscode/*.json"
      - ".editorconfig"

":book: Document":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.xml"
      - "**/*.md"

":page_facing_up: Locale":
  - changed-files:
    - any-glob-to-any-file: 'Resources/Locale/**/*.ftl'

":world_map: Maps":
  - changed-files:
    - any-glob-to-any-file:
      - "Resources/Maps/**/*.yml"
      - "Resources/Prototypes/Maps/**/*.yml"

":art: Sprite":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.rsi/*.png"
      - "**/*.rsi/*.json"

":computer: UI":
  - changed-files:
    - any-glob-to-any-file: "**/*.xaml*"

":baby_chick: YML":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.yml"
    - all-globs-to-all-files:
      - "!Resources/Maps/**/*.yml"
      - "!Resources/Prototypes/Maps/**/*.yml"

":wrench: GitHub Workflow":
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/*.yml"

":crystal_ball: Shader":
  - changed-files:
    - any-glob-to-any-file: '**/*.swsl'

":no_entry: No C#":
  - changed-files:
    - all-globs-to-all-files: "!**/*.cs"
